vqa_root: './dataset/mscoco/' #followed by train2014/
vg_root: './dataset/VG_100K/' #followed by image/
train_files: ['vqa_train']
ann_root: './dataset/VQA2.0/annotations/'

# set pretrained as a file path or an url
pretrained: './download_model/BLIP/model_base_capfilt_large.pth'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0

batch_size_train: 8
batch_size_test: 4
image_size: 224
text_len: 40

freeze: True

# Adapter
add_text_ffn_adapter: True
text_ffn_adapter_reduction_factor: 8

add_text_laplacian_adapter: True
learnable_p: True
laplacian_adapter_p_self : 1.25
laplacian_adapter_p_cross : 1.25
laplacian_adapter_mu : 0.1
text_laplacian_adapter_reduction_factor: 8
image_sample_len : 16

add_query_adapter: False
add_key_adapter: False
lora_r: 8
lora_alpha: 32

inference: 'rank'

# generation eff_blip_configs
max_length: 50
min_length: 1
num_beams: 3

# rank eff_blip_configs
k_test: 32

# optimizer & scheduler
lr: 5e-4
weight_decay: 0.05
max_epoch: 5
warmup_ratio: 0
